# Generated by Django 3.1.4 on 2020-12-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20201208_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(default='A', max_length=30),
            preserve_default=False,
        ),
    ]
