# Generated by Django 3.1.4 on 2020-12-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.URLField(default='https://i.pinimg.com/originals/51/f6/fb/51f6fb256629fc755b8870c801092942.png'),
        ),
    ]
