# Generated by Django 3.1.4 on 2020-12-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_student_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
