# Generated by Django 3.1.4 on 2020-12-14 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='avaible_in_countries',
            field=models.ManyToManyField(max_length=100, related_name='avaible_in_countries', to='film_app.Country'),
        ),
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(max_length=100, to='film_app.Category'),
        ),
        migrations.AlterField(
            model_name='film',
            name='created_in_country',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='created_in_country', to='film_app.country'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(max_length=100, to='film_app.Director'),
        ),
    ]
